# Generated by Django 3.1.3 on 2020-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
