# Generated by Django 3.1.3 on 2020-11-28 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0002_auto_20201128_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
