# Generated by Django 3.1.3 on 2020-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih', '0003_auto_20201128_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='customer_phonenumber',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
